import {setProducts, setStoreName, setDocName, setNumProducts, getNavigator, validateNav, main, body, header, ad, productCount, productMainContainer, storeNavigation, sideNavigation, openMenu, pageName, storeTitle, pageLink, price, productLink, description, img, myProductArray, rating } from "../Store/Store_Blueprint.mjs";
import { companyInfo, navLinks, icons, attribute, navbar, footer, footerForm, footerInput, footerLabel, footerResponse, footerBtn, date, urlPath, linkCSS } from "../Nav&Footer_Blueprint.mjs";

// Product Attributes
price.insertAtHead(59.99);
price.insertAtHead(59.99);
price.insertAtHead(32.98);
price.insertAtHead(24.99);
price.insertAtHead(47.89);
price.insertAtHead(59.99);
price.insertAtHead(22.89);
price.insertAtHead(58.99);
price.insertAtHead(19.99);
price.insertAtHead(49.99);
price.insertAtHead(4.99);
price.insertAtHead(4.99);
price.insertAtHead(4.99);
price.insertAtHead(4.99);
price.insertAtHead(4.99);
price.insertAtHead(4.99);
price.insertAtHead(19.99);
price.insertAtHead(249.99);
price.insertAtHead(67.89);
price.insertAtHead(4.65);
price.insertAtHead(59.99);
price.insertAtHead(34.95);
price.insertAtHead(22.89);
price.insertAtHead(8.59);
price.insertAtHead(10.99);

img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_1.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_2.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_3.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_4.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_5.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_6.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_7.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_8.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_9.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_10.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_11.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_12.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_13.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_14.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_15.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_16.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_17.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_18.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_19.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_20.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_21.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_22.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_23.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_24.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 3/Product_25.jpg`);

description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');
description.insertAtHead('');

productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_1.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_2.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_3.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_4.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_5.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_6.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_7.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_8.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_9.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_10.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_11.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_12.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_13.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_14.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_15.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_16.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_17.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_18.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_19.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_20.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_21.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_22.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_23.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_24.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 3/product_25.html`);

header[0].remove();
ad[0].remove();
body[0].classList.add("changeBody");
productMainContainer.classList.add('positionMain');
storeNavigation.innerHTML = getNavigator(2);

validateNav(2);
setProducts(img);
setNumProducts(myProductArray.length);
setDocName("Palmer Studios Store | Page 3");