import {setProducts, setStoreName, setDocName, setNumProducts, getNavigator, validateNav, generateId, main, body, header, ad, productCount, productMainContainer, storeNavigation, sideNavigation, openMenu, pageName, storeTitle, pageLink, price, productLink, description, img, myProductArray, rating } from "../Store/Store_Blueprint.mjs";
import { companyInfo, navLinks, icons, attribute, navbar, footer, footerForm, footerInput, footerLabel, footerResponse, footerBtn, date, urlPath, linkCSS } from "../Nav&Footer_Blueprint.mjs";

// Product Attributes
price.insertAtHead(42.99);
price.insertAtHead(13.99);
price.insertAtHead(2.99);
price.insertAtHead(10.99);
price.insertAtHead(13.99);
price.insertAtHead(7.99);
price.insertAtHead(1129.99);
price.insertAtHead(4.99);
price.insertAtHead(15.99);
price.insertAtHead(69.99);
price.insertAtHead(56.99);
price.insertAtHead(43.99);
price.insertAtHead(28.49);
price.insertAtHead(15.25);
price.insertAtHead(16.59);
price.insertAtHead(49.99);
price.insertAtHead(49.99);
price.insertAtHead(7.99);
price.insertAtHead(12.82);
price.insertAtHead(15.59);
price.insertAtHead(125);
price.insertAtHead(16.99);
price.insertAtHead(20.00);
price.insertAtHead(46.99);
price.insertAtHead(24.99);
price.insertAtHead(3590.89);
price.insertAtHead(20.00);

img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_27.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_1.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_2.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_3.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_4.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_5.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_6.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_7.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_8.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_9.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_10.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_11.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_12.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_13.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_14.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_15.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_16.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_17.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_18.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_19.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_20.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_21.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_22.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_23.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_24.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_25.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 2/Product_4.jpg`);

description.insertAtHead('Black African American Heritage Flag');
description.insertAtHead('Black Lives Matter T-Shirt | Black');
description.insertAtHead('Black Lives Matter Wristbands');
description.insertAtHead('Black Lives Matter Metal Souvenir');
description.insertAtHead('Black Lives Matter T-Shirt | Cotton Material');
description.insertAtHead('Black Lives Matter Face Mask');
description.insertAtHead('Canon 6D Mark II Camera with EF 24-105mm USM Lens, WiFi Enabled | Matt Black');
description.insertAtHead('Professional Black Carbon Fiber Hair Combs Salon Grade Combo Comb Set');
description.insertAtHead('Mens Turtleneck Slim Top | Black');
description.insertAtHead('Beautiful Womens Solid Slim Bodysuit Outfit');
description.insertAtHead('Solid Turtleneck Bodycon Dress');
description.insertAtHead('Solid Outdoor Slim Dress');
description.insertAtHead('TROJAN Pleasure Pack, 40 Assorted Condoms');
description.insertAtHead('Durex Real Feel Non-Latex Condoms');
description.insertAtHead('Trojan ENZ Condoms For Contraception Plus STI Protection, 36 Count, 1 Pack');
description.insertAtHead('Taylor All Star Lift Platform Leather Converse | Black');
description.insertAtHead('Taylor All Star Lift Platform Leather Converse | White');
description.insertAtHead(`Smart & Sexy Women's Signature Lace Unlined Underwire Longline Bra`);
description.insertAtHead('KY - Liquid Water-Based Personal Lubricant');
description.insertAtHead('Acqua Di Gio Giorgio Armani Profumo');
description.insertAtHead('Nike - Air Jordan 1 Mid');
description.insertAtHead('Black Lives Matter Beaded Bracelet');
description.insertAtHead('African Dashiki - White | Forest Green Triangle Design African Suiting and Cotton Fabrics');
description.insertAtHead('African Dashiki - Forest Green | African Lace, Suiting, and Cotton Fabric');
description.insertAtHead('African Dashiki - Orange | African Print Brocade, Silk, Lace, Suiting, and Cotton Fabric');
description.insertAtHead('Dimond Wedding Ring');
description.insertAtHead('Black Lives Matter T-Shirt');

productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_1.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_1.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_2.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_3.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_4.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_5.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_6.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_7.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_8.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_9.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_10.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_11.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_12.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_13.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_14.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_15.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_16.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_17.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_18.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_19.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_20.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_21.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_22.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_23.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_24.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_25.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 2/product_25.html`);


header[0].remove();
ad[0].remove();
body[0].classList.add("changeBody");
productMainContainer.classList.add('positionMain');
storeNavigation.innerHTML = getNavigator(1);
validateNav(1);
setProducts(img, 3846);
setNumProducts(myProductArray.length);
setDocName("Palmer Studios Store | Page 2");

console.log(myProductArray);