import {setProducts, setStoreName, setDocName, setNumProducts, getNavigator, validateNav, main, body, header, ad, productCount, productMainContainer, storeNavigation, sideNavigation, openMenu, pageName, storeTitle, pageLink, price, productLink, description, img, myProductArray, rating } from "../Store/Store_Blueprint.mjs";
import { companyInfo, navLinks, icons, attribute, navbar, footer, footerForm, footerInput, footerLabel, footerResponse, footerBtn, date, urlPath, linkCSS } from "../Nav&Footer_Blueprint.mjs";

// Product Attributes
price.insertAtHead(24.99);
price.insertAtHead(15.99);
price.insertAtHead(34.99);
price.insertAtHead(34.99);
price.insertAtHead(13.99);
price.insertAtHead(11.99);
price.insertAtHead(10.25);
price.insertAtHead(15.99);
price.insertAtHead(39.99);
price.insertAtHead(5.99);
price.insertAtHead(3.99);
price.insertAtHead(5.65);
price.insertAtHead(15.25);
price.insertAtHead(23.45);
price.insertAtHead(10.25);
price.insertAtHead(6.99);
price.insertAtHead(12.99);
price.insertAtHead(12.82);
price.insertAtHead(15.59);
price.insertAtHead(14.99);
price.insertAtHead(35.99);
price.insertAtHead(20.00);
price.insertAtHead(6.45);
price.insertAtHead(13.99);
price.insertAtHead(25.89);

img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_1.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_2.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_3.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_4.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_5.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_6.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_7.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_8.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_9.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_10.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_11.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_12.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_13.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_14.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_15.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_16.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_17.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_18.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_19.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_20.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_21.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_22.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_23.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_24.jpg`);
img.insertAtHead(`${urlPath}/IMG/Store Products/Store 1/Product_25.jpg`);

description.insertAtHead('Light Gray Palmer Hoodie');
description.insertAtHead('White Palmer T-Shirt - Hustlers');
description.insertAtHead('Keke Palmer Duvet Set (Purple)');
description.insertAtHead('Keke Palmer Duvet Set (Tan)');
description.insertAtHead('Keke Palmer T-Shirt (White)');
description.insertAtHead('Keke Do You Love Me T-Shirt');
description.insertAtHead('Black and Brown Exfoliating Cleanser');
description.insertAtHead('African Clarifying Mud Mask Oils and Spray');
description.insertAtHead('Skin Safe Manscaping Trimmer');
description.insertAtHead('Hair Sponge Brush for Twists and Locks (Black)');
description.insertAtHead('Classic Styling Essential Compact Comb (Black)');
description.insertAtHead('Hair Brush Wooden Paddle Hairbrush Detangling Hairbrush');
description.insertAtHead('Savanna Grass - Album By Kes');
description.insertAtHead('Nyraju Natural Skincare Serum For Acne (Cleanser and Toner)');
description.insertAtHead('Blueberry Bliss Curl Control Jelly');
description.insertAtHead('African  Black Soap 6 fl oz');
description.insertAtHead('Curl Love Moisture Milk (Rice Milk and Macadamia Oil)');
description.insertAtHead('Hair Picks (3 Count)');
description.insertAtHead('Conditioner, Treatment, Detangling Spray, and Shampoo');
description.insertAtHead('Buttah AHA | BHA Rosewater Toner');
description.insertAtHead('Champion Adult Mens Everyday Comfort Boxer Underwear');
description.insertAtHead('Womens Comfort Stretch Brief Panties (Black)');
description.insertAtHead('Womens Underwear Soft Breathable Panties Stretch Hipsters (Black)');
description.insertAtHead('Mens Black Boxer Briefs Cotton Stretchy Underwear (5 Pack)');
description.insertAtHead('Womens Padded Butt Lifter Hip Enhancer Shaper Panties Underwear');

productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_1.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_2.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_3.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_4.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_5.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_6.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_7.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_8.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_9.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_10.htm`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_11.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_12.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_13.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_14.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_15.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_16.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_17.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_18.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_19.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_20.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_21.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_22.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_23.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_24.html`);
productLink.insertAtHead(`${urlPath}/HTML/Store/Page 1/product_25.html`);

storeNavigation.innerHTML = getNavigator(0);
validateNav(0);
setProducts(img);
setNumProducts(myProductArray.length);
setDocName("Palmer Studios Store | Page 1");
console.log(myProductArray);